- name: create_directory
  hosts: all
  tasks:
   - name: Hello World!
     debug: 
       msg: "Hi! Tower is working!"
   - name: Creates directory
     file:
       path: ~/demo_directory_created_through_awx
       state: directory
